# Generated by Django 6.0 on 2025-12-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_order_total_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
