# Generated by Django 6.0 on 2025-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
