# Generated by Django 6.0 on 2025-12-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_item_total_quantity_order_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Pending'), ('Оплачен', 'Paid'), ('Отправлен', 'Shipped'), ('Доставлен', 'Delivered'), ('Отменен', 'Cancelled')], default='Ожидает оплаты', max_length=15),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('rel_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.order')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='items.orderitem'),
        ),
    ]
