# Generated by Django 6.0 on 2025-12-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_quantity_remove_order_total_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='rel_order',
        ),
    ]
