# Generated by Django 6.0 on 2025-12-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_order_items_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'euro'), ('RUB', 'rub')], default='USD', max_length=4),
        ),
    ]
