# Generated by Django 6.0 on 2025-12-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_orderitem_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'euro'), ('RUB', 'rub')], default='USD', max_length=4),
        ),
    ]
