# Generated by Django 6.0 on 2025-12-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_orderitem_currency_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'euro')], default='USD', max_length=4),
        ),
    ]
