# Generated by Django 6.0 on 2025-12-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_item_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_percent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.discount'),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.tax'),
        ),
    ]
