# Generated by Django 6.0 on 2025-12-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_discount_order_discount_percent_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order_id',
        ),
    ]
