# Generated by Django 6.0 on 2025-12-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_remove_discount_order_id_remove_tax_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_percent',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax_percent',
            new_name='tax',
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tax',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
