# Generated by Django 6.0 on 2025-12-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_rename_discount_percent_order_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'usd'), ('EUR', 'euro')], default='USD', max_length=4),
        ),
    ]
